"use client"

/**
 * Maps each catalog route to its live demo so the gallery can render the real
 * component as a scaled thumbnail (Mobbin-style). Overlay / portal / keyboard
 * components are intentionally omitted — they render a branded placeholder card
 * instead of escaping their frame.
 */

import type { ComponentType } from "react"
import {
  DemoAnalyticsProvider,
  DemoArPortfolio,
  DemoBoldFooter,
  DemoBreadcrumbs,
  DemoButton,
  DemoCalendlyEmbed,
  DemoCard,
  DemoChangelog,
  DemoCommandMenuGallery,
  DemoContextualCta,
  DemoCountUp,
  DemoDeadlineCountdown,
  DemoAccordion,
  DemoAutocomplete,
  DemoCheckbox,
  DemoCheckboxGroup,
  DemoCollapsible,
  DemoCombobox,
  DemoField,
  DemoFieldset,
  DemoForm,
  DemoInput,
  DemoNumberField,
  DemoOtpField,
  DemoRadio,
  DemoSwitch,
  DemoAvatar,
  DemoMeter,
  DemoSlider,
  DemoProgress,
  DemoTabs,
  DemoToggle,
  DemoToggleGroup,
  DemoToolbar,
  DemoExitIntentPopup,
  DemoFadeIn,
  DemoFadeInSection,
  DemoFaqInteractivePreview,
  DemoFeatureGrid,
  DemoFormSelect,
  DemoFounderAvatar,
  DemoHomeCrafts,
  DemoHomeHero,
  DemoHomeLab,
  DemoHomePrinciple,
  DemoHomeWho,
  DemoHomeWork,
  DemoJournalContent,
  DemoLabelRoll,
  DemoLineReveal,
  DemoWordRevealScroll,
  DemoLiveDashboard,
  DemoLocalClock,
  DemoLogo,
  DemoLogoCloud,
  DemoMadeWithEmbed,
  DemoMagnetic,
  DemoNewsletterForm,
  DemoOgExamples,
  DemoOgLivePreview,
  DemoOgWorkspace,
  DemoPersonalHero,
  DemoPricingOverview,
  DemoProjectList,
  DemoProjectPlanner,
  DemoProse,
  DemoResourcesContent,
  DemoResume,
  DemoScopeChat,
  DemoScrollArea,
  DemoScrollProgress,
  DemoSeparator,
  DemoSiteFooter,
  DemoSiteHeader,
  DemoSocialShare,
  DemoSpotlight,
  DemoStagger,
  DemoTextarea,
  DemoTextMorph,
  DemoCopyButton,
  DemoAnimateNumber,
  DemoTransitionPanel,
  DemoThemeAdapt,
  DemoThemeProviderNote,
  DemoThemeToggle,
  DemoThumbnailLivePreview,
  DemoThumbnailWorkspace,
  DemoTilt,
  DemoTimelineAnimation,
  DemoWaitlistForm,
  DemoWeatherChip,
} from "@/components/registry-demos"

export const previewRegistry: Record<string, ComponentType> = {
  // Primitives
  "/docs/components/ui-button": DemoButton,
  // Overlay portals omitted from gallery thumbs (escape frame) — demos live on docs pages
  "/docs/components/ui-accordion": DemoAccordion,
  "/docs/components/ui-autocomplete": DemoAutocomplete,
  "/docs/components/ui-checkbox": DemoCheckbox,
  "/docs/components/ui-checkbox-group": DemoCheckboxGroup,
  "/docs/components/ui-collapsible": DemoCollapsible,
  "/docs/components/ui-combobox": DemoCombobox,
  "/docs/components/ui-field": DemoField,
  "/docs/components/ui-number-field": DemoNumberField,
  "/docs/components/ui-otp-field": DemoOtpField,
  "/docs/components/ui-form": DemoForm,
  "/docs/components/ui-fieldset": DemoFieldset,
  "/docs/components/ui-input": DemoInput,
  "/docs/components/ui-radio": DemoRadio,
  "/docs/components/ui-switch": DemoSwitch,
  "/docs/components/ui-avatar": DemoAvatar,
  "/docs/components/ui-meter": DemoMeter,
  "/docs/components/ui-slider": DemoSlider,
  "/docs/components/ui-progress": DemoProgress,
  "/docs/components/ui-tabs": DemoTabs,
  "/docs/components/ui-toggle": DemoToggle,
  "/docs/components/ui-toggle-group": DemoToggleGroup,
  "/docs/components/ui-toolbar": DemoToolbar,
  "/docs/components/ui-card": DemoCard,
  "/docs/components/ui-form-select": DemoFormSelect,
  "/docs/components/ui-textarea": DemoTextarea,
  "/docs/components/ui-scroll-area": DemoScrollArea,
  "/docs/components/ui-separator": DemoSeparator,
  "/docs/components/ui-breadcrumbs": DemoBreadcrumbs,
  "/docs/components/ui-prose": DemoProse,
  "/docs/components/ui-founder-avatar": DemoFounderAvatar,
  "/docs/components/ui-theme-toggle": DemoThemeToggle,
  "/docs/components/ui-theme-adapt": DemoThemeAdapt,
  "/docs/components/theme-provider": DemoThemeProviderNote,
  "/docs/components/brand-logo": DemoLogo,
  "/docs/components/ui-timeline-animation": DemoTimelineAnimation,
  "/docs/components/motion-fade-in": DemoFadeIn,
  "/docs/components/motion-in-view": DemoFadeInSection,
  "/docs/components/motion-stagger": DemoStagger,
  "/docs/components/motion-line-reveal": DemoLineReveal,
  "/docs/components/motion-word-reveal-scroll": DemoWordRevealScroll,
  "/docs/components/motion-text-morph": DemoTextMorph,
  "/docs/components/motion-copy-button": DemoCopyButton,
  "/docs/components/motion-label-roll": DemoLabelRoll,
  "/docs/components/motion-magnetic": DemoMagnetic,
  "/docs/components/motion-tilt": DemoTilt,
  "/docs/components/motion-spotlight": DemoSpotlight,
  "/docs/components/motion-animate-number": DemoAnimateNumber,
  "/docs/components/motion-transition-panel": DemoTransitionPanel,
  "/docs/components/motion-primitives-scroll-progress": DemoScrollProgress,

  // Blocks
  "/docs/components/site-header": DemoSiteHeader,
  "/docs/components/site-footer": DemoSiteFooter,
  "/docs/components/footer-bold": DemoBoldFooter,
  "/docs/components/home-hero": DemoHomeHero,
  "/docs/components/home-principle": DemoHomePrinciple,
  "/docs/components/home-work": DemoHomeWork,
  "/docs/components/home-crafts": DemoHomeCrafts,
  "/docs/components/home-lab": DemoHomeLab,
  "/docs/components/home-who": DemoHomeWho,
  "/docs/components/pricing-overview": DemoPricingOverview,
  "/docs/components/feature-grid": DemoFeatureGrid,
  "/docs/components/logo-cloud": DemoLogoCloud,
  "/docs/components/faq-interactive-preview": DemoFaqInteractivePreview,
  "/docs/components/cta-contextual-cta": DemoContextualCta,
  "/docs/components/cta-exit-intent-popup": DemoExitIntentPopup,
  "/docs/components/contact-calendly-embed": DemoCalendlyEmbed,
  "/docs/components/brand-waitlist-form": DemoWaitlistForm,
  "/docs/components/newsletter-newsletter-form": DemoNewsletterForm,
  "/docs/components/journal-journal-content": DemoJournalContent,
  "/docs/components/journal-social-share": DemoSocialShare,
  "/docs/components/resources-resources-content": DemoResourcesContent,
  "/docs/components/ar-ar-portfolio": DemoArPortfolio,
  "/docs/components/seo-made-with-embed": DemoMadeWithEmbed,

  // Indie
  "/docs/components/count-up": DemoCountUp,
  "/docs/components/deadline-countdown": DemoDeadlineCountdown,
  "/docs/components/project-list": DemoProjectList,
  "/docs/components/changelog": DemoChangelog,
  "/docs/components/personal-hero": DemoPersonalHero,
  "/docs/components/resume": DemoResume,
  "/docs/components/local-clock": DemoLocalClock,
  "/docs/components/weather-chip": DemoWeatherChip,
  "/docs/components/command-menu": DemoCommandMenuGallery,

  // Tools
  "/docs/components/og-og-examples": DemoOgExamples,
  "/docs/components/og-og-live-preview": DemoOgLivePreview,
  "/docs/components/og-og-workspace": DemoOgWorkspace,
  "/docs/components/thumbnail-thumbnail-live-preview": DemoThumbnailLivePreview,
  "/docs/components/thumbnail-thumbnail-workspace": DemoThumbnailWorkspace,
  "/docs/components/planner-project-planner": DemoProjectPlanner,
  "/docs/components/scope-scope-chat": DemoScopeChat,
  "/docs/components/studio-live-dashboard": DemoLiveDashboard,

  // Headless
  "/docs/components/analytics-analytics-provider": DemoAnalyticsProvider,
}
