"use client"

/**
 * Maps each catalog route to its live demo so the gallery can render the real
 * component as a scaled thumbnail (Mobbin-style). Overlay / portal / keyboard
 * components are intentionally omitted — they render a branded placeholder card
 * instead of escaping their frame.
 */

import type { ComponentType } from "react"
import {
  DemoAnalyticsProvider,
  DemoArPortfolio,
  DemoBeforeAfterSlider,
  DemoBoldFooter,
  DemoBreadcrumbs,
  DemoButton,
  DemoCalendlyEmbed,
  DemoCard,
  DemoChangelog,
  DemoContactForm,
  DemoContextualCta,
  DemoCountUp,
  DemoCurrently,
  DemoDeadlineCountdown,
  DemoExitIntentPopup,
  DemoFadeIn,
  DemoFaqInteractivePreview,
  DemoFeatureGrid,
  DemoFormSelect,
  DemoFounderAvatar,
  DemoHomeCrafts,
  DemoHomeHero,
  DemoHomeLab,
  DemoHomePrinciple,
  DemoHomeWho,
  DemoHomeWork,
  DemoJournalContent,
  DemoJsonLd,
  DemoLiveDashboard,
  DemoLocalClock,
  DemoLogPreview,
  DemoLogo,
  DemoLogoCloud,
  DemoMadeWithEmbed,
  DemoNewsletterForm,
  DemoOgExamples,
  DemoOgLivePreview,
  DemoOgWorkspace,
  DemoPersonalHero,
  DemoPricingOverview,
  DemoProjectList,
  DemoProjectPlanner,
  DemoProse,
  DemoReadingShelf,
  DemoResourcesContent,
  DemoResume,
  DemoReveal,
  DemoScopeChat,
  DemoScrollProgress,
  DemoSiteFooter,
  DemoSiteFooterNarrow,
  DemoSiteHeader,
  DemoSiteHeaderNarrow,
  DemoSocialShare,
  DemoStackList,
  DemoStagger,
  DemoTestimonialSchema,
  DemoTextarea,
  DemoThemeAdapt,
  DemoThemeProviderNote,
  DemoThemeToggle,
  DemoThemeToggleIcon,
  DemoThumbnailLivePreview,
  DemoThumbnailWorkspace,
  DemoTimelineAnimation,
  DemoUiMockupFrame,
  DemoVisualCaseStudy,
  DemoWaitlistForm,
  DemoWeatherChip,
} from "@/components/registry-demos"

export const previewRegistry: Record<string, ComponentType> = {
  // Primitives
  "/docs/components/ui-button": DemoButton,
  "/docs/components/ui-card": DemoCard,
  "/docs/components/ui-form-select": DemoFormSelect,
  "/docs/components/ui-textarea": DemoTextarea,
  "/docs/components/ui-breadcrumbs": DemoBreadcrumbs,
  "/docs/components/ui-prose": DemoProse,
  "/docs/components/ui-founder-avatar": DemoFounderAvatar,
  "/docs/components/ui-theme-toggle": DemoThemeToggle,
  "/docs/components/ui-theme-adapt": DemoThemeAdapt,
  "/docs/components/theme-provider": DemoThemeProviderNote,
  "/docs/components/brand-logo": DemoLogo,
  "/docs/components/ui-ui-mockup-frame": DemoUiMockupFrame,
  "/docs/components/ui-timeline-animation": DemoTimelineAnimation,
  "/docs/components/motion-fade-in": DemoFadeIn,
  "/docs/components/motion-stagger": DemoStagger,
  "/docs/components/motion-primitives-scroll-progress": DemoScrollProgress,

  // Blocks
  "/docs/components/site-header": DemoSiteHeader,
  "/docs/components/site-footer": DemoSiteFooter,
  "/docs/components/footer-bold": DemoBoldFooter,
  "/docs/components/home-hero": DemoHomeHero,
  "/docs/components/home-principle": DemoHomePrinciple,
  "/docs/components/home-work": DemoHomeWork,
  "/docs/components/home-crafts": DemoHomeCrafts,
  "/docs/components/home-lab": DemoHomeLab,
  "/docs/components/home-who": DemoHomeWho,
  "/docs/components/pricing-overview": DemoPricingOverview,
  "/docs/components/feature-grid": DemoFeatureGrid,
  "/docs/components/logo-cloud": DemoLogoCloud,
  "/docs/components/faq-interactive-preview": DemoFaqInteractivePreview,
  "/docs/components/cta-contextual-cta": DemoContextualCta,
  "/docs/components/cta-exit-intent-popup": DemoExitIntentPopup,
  "/docs/components/contact-contact-form": DemoContactForm,
  "/docs/components/contact-calendly-embed": DemoCalendlyEmbed,
  "/docs/components/brand-waitlist-form": DemoWaitlistForm,
  "/docs/components/newsletter-newsletter-form": DemoNewsletterForm,
  "/docs/components/journal-journal-content": DemoJournalContent,
  "/docs/components/journal-social-share": DemoSocialShare,
  "/docs/components/resources-resources-content": DemoResourcesContent,
  "/docs/components/case-studies-before-after-slider": DemoBeforeAfterSlider,
  "/docs/components/case-studies-visual-case-study": DemoVisualCaseStudy,
  "/docs/components/ar-ar-portfolio": DemoArPortfolio,
  "/docs/components/seo-made-with-embed": DemoMadeWithEmbed,

  // Indie
  "/docs/components/count-up": DemoCountUp,
  "/docs/components/deadline-countdown": DemoDeadlineCountdown,
  "/docs/components/currently": DemoCurrently,
  "/docs/components/project-list": DemoProjectList,
  "/docs/components/log-preview": DemoLogPreview,
  "/docs/components/changelog": DemoChangelog,
  "/docs/components/reveal": DemoReveal,
  "/docs/components/theme-toggle-icon": DemoThemeToggleIcon,
  "/docs/components/site-header-narrow": DemoSiteHeaderNarrow,
  "/docs/components/site-footer-narrow": DemoSiteFooterNarrow,
  "/docs/components/reading-shelf": DemoReadingShelf,
  "/docs/components/personal-hero": DemoPersonalHero,
  "/docs/components/resume": DemoResume,
  "/docs/components/local-clock": DemoLocalClock,
  "/docs/components/weather-chip": DemoWeatherChip,
  "/docs/components/stack-list": DemoStackList,

  // Tools
  "/docs/components/og-og-examples": DemoOgExamples,
  "/docs/components/og-og-live-preview": DemoOgLivePreview,
  "/docs/components/og-og-workspace": DemoOgWorkspace,
  "/docs/components/thumbnail-thumbnail-live-preview": DemoThumbnailLivePreview,
  "/docs/components/thumbnail-thumbnail-workspace": DemoThumbnailWorkspace,
  "/docs/components/planner-project-planner": DemoProjectPlanner,
  "/docs/components/scope-scope-chat": DemoScopeChat,
  "/docs/components/studio-live-dashboard": DemoLiveDashboard,

  // Headless
  "/docs/components/analytics-analytics-provider": DemoAnalyticsProvider,
  "/docs/components/seo-json-ld": DemoJsonLd,
  "/docs/components/seo-testimonial-schema": DemoTestimonialSchema,
}
