/**
 * AUTO-GENERATED by scripts/generate-post.ts - do not edit manually.
 * MDX loaders only — import from `atroui/lib/articles-loaders` (or this file)
 * in apps that configure MDX. Do not import from the main `atroui` barrel path
 * used by UI consumers.
 */

import type { ComponentType } from "react";

export const JOURNAL_LOADERS: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
  "building-a-cost-efficient-ai-powered-saas-mvp-next-js-16-edge-functions-with-loc": () =>
    import("./building-a-cost-efficient-ai-powered-saas-mvp-next-js-16-edge-functions-with-loc.mdx"),
  "building-a-real-time-ai-summarization-saas-mvp-with-next-js-server-actions-strea": () =>
    import("./building-a-real-time-ai-summarization-saas-mvp-with-next-js-server-actions-strea.mdx"),
  "designing-hyper-efficient-ai-mvps-a-tailwind-v4-guide-for-next-js-16-react-19-in": () =>
    import("./designing-hyper-efficient-ai-mvps-a-tailwind-v4-guide-for-next-js-16-react-19-in.mdx"),
};
