/**
 * AUTO-GENERATED by scripts/generate-post.ts — do not edit manually.
 * Rebuilt when new journal MDX files are created.
 */

import type { ComponentType } from "react";

import type { ArticleMeta } from "../../lib/articles";

export const JOURNAL_ARTICLES: ArticleMeta[] = [
  {
    slug: "building-a-cost-efficient-ai-powered-saas-mvp-next-js-16-edge-functions-with-loc",
    title: "Building a Cost-Efficient AI-Powered SaaS MVP: Next.js 16 Edge Functions with Local Model Inference",
    description: "Slash AI API costs for your SaaS MVP. Learn to leverage Next.js Edge Functions with local model inference (Ollama, Transformers.js) for faster, cheaper, and more private AI features.",
    date: "2026-06-23",
    tag: "Guide",
    category: "AI",
    readTime: "9 min read",
    author: "Koustav",
  },
  {
    slug: "building-a-real-time-ai-summarization-saas-mvp-with-next-js-server-actions-strea",
    title: "Building a Real-time AI Summarization SaaS MVP with Next.js Server Actions, Streaming, and Vercel AI SDK",
    description: "Launch your AI summarization SaaS MVP fast. Use Next.js 16 Server Actions, Vercel AI SDK, and backend streaming for efficient, developer-friendly builds.",
    date: "2026-06-23",
    tag: "Guide",
    category: "Development",
    readTime: "7 min read",
    author: "Koustav",
  },
  {
    slug: "designing-hyper-efficient-ai-mvps-a-tailwind-v4-guide-for-next-js-16-react-19-in",
    title: "Designing Hyper-Efficient AI MVPs: A Tailwind v4 Guide for Next.js 16 & React 19 Indie Projects",
    description: "Build lightning-fast AI MVPs with Next.js 16, React 19, and Tailwind v4. Learn practical design patterns and code snippets for indie founders.",
    date: "2026-06-22",
    tag: "Guide",
    category: "Development",
    readTime: "5 min read",
    author: "Koustav",
  },
];

export const JOURNAL_LOADERS: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
  "building-a-cost-efficient-ai-powered-saas-mvp-next-js-16-edge-functions-with-loc": () => import("./building-a-cost-efficient-ai-powered-saas-mvp-next-js-16-edge-functions-with-loc.mdx"),
  "building-a-real-time-ai-summarization-saas-mvp-with-next-js-server-actions-strea": () => import("./building-a-real-time-ai-summarization-saas-mvp-with-next-js-server-actions-strea.mdx"),
  "designing-hyper-efficient-ai-mvps-a-tailwind-v4-guide-for-next-js-16-react-19-in": () => import("./designing-hyper-efficient-ai-mvps-a-tailwind-v4-guide-for-next-js-16-react-19-in.mdx"),
};
